# -*- coding: utf-8 -*-
"""ProvaSub - Postech - Data Analytics - Fase 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usKa-R9Ll6ALlkiALKDo1lsAwYvCGXzG
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

